Add fix for slow Elasticsearch API
See also
https://discuss.elastic.co/t/error-during-elasticsearch-deployment-via-puppet/108008

In order to fix the idempotence, where Puppet failed on the first run
due to a message:

  Error: Failed to apply catalog: Connection refused - connect(2) for
"localhost" port 9200

I increased the api_timeout from 10 to 120 and changed the localhost to
0.0.0.0 (which seemed necessary on my VM, but I'm not totally sure it
actually was required).